# Generated by Django 5.2.6 on 2025-10-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
