# Generated by Django 5.2.6 on 2025-11-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
