# Generated by Django 5.2.6 on 2025-11-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_produto_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comprado', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('vacina', 'Vacina'), ('consulta', 'Consulta'), ('medicamento', 'Medicamento'), ('higiene', 'Higiene'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meta',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='meta',
            name='progresso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_compras', to='pets.pet'),
        ),
    ]
