# Generated by Django 5.2.6 on 2025-10-19 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='concluida',
        ),
        migrations.AddField(
            model_name='meta',
            name='progresso',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
